name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: '${{ matrix.platform }} with Java 8'
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 8
      - name: Build and Test
        run: mvn -B package
