name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: '${{ matrix.platform }} with Java ${{ matrix.java-version }}'
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java-version:
          - 8
          - 11
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: ${{ matrix.java-version }}
      - name: Build and Test
        run: mvn -B package
